// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVisualStudioCode
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenInVisualStudioCode.f630dc87-7db5-4e82-96da-01c828d2bdac";
        public const string Name = "OpenInVisualStudioCode";
        public const string Description = @"Visual Studio extension to open file or folder in Visual Studio Code.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Paulius Piečius";
        public const string Tags = "Visual Studio Code";
    }
}
