// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVisualStudioCode
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OpenInVisualStudioCodeString = "f43ff903-ed38-49fa-9f06-fcb1c1cdc69d";
        public static Guid OpenInVisualStudioCode = new Guid(OpenInVisualStudioCodeString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenInVSCodeGroup = 0x0001;
        public const int OpenInVSCode = 0x0100;
    }
}